// vue-vuex/src/components/MdEditor.vue
<template>
  <div class="container">
    <AceEditor
      :value="content"
      @input="$emit('change', $event)"
      @init="init"
      lang="markdown"
      theme="monokai"
    />
  </div>
</template>

<script>
import AceEditor from "vue2-ace-editor";
import "brace/mode/markdown";
import "brace/theme/monokai";

export default {
  components: {
    AceEditor
  },
  model: {
    prop: "content",
    event: "change"
  },
  props: {
    content: { type: String, default: "" }
  },
  methods: {
    init(editor) {
      editor.renderer.setScrollMargin(6, 0);
      editor.setOptions({
        printMargin: false,
        wrap: true,
        scrollPastEnd: 0.5,
        fontSize: "16px"
      });
    }
  }
};
</script>

<style scoped>
.container {
  display: flex;
  flex: 1;
}
</style>

// react-redux/src/components/MdEditor.js
import React, { Component } from "react";
import AceEditor from "react-ace";
import PropTypes from "prop-types";
import "brace/mode/markdown";
import "brace/theme/monokai";

const styles = {
  editor: {
    background: "red",
    display: "flex",
    flex: 1,
    overflow: "hidden"
  }
};

class MdEditor extends Component {
  componentDidMount() {
    this.aceRef.editor.renderer.setScrollMargin(6, 0);
  }

  render() {
    return (
      <div style={styles.editor}>
        <AceEditor
          ref={e => (this.aceRef = e)}
          mode="markdown"
          theme="monokai"
          value={this.props.content}
          onChange={this.props.onChange}
          setOptions={{
            printMargin: false,
            wrap: true,
            scrollPastEnd: 0.5,
            fontSize: "16px"
          }}
          width="100%"
          height="100%"
        />
      </div>
    );
  }
}

MdEditor.propTypes = {
  content: PropTypes.string,
  onChange: PropTypes.func
};

export default MdEditor;
